# Generated by Django 5.1.6 on 2025-03-01 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0002_resume_experience_education_certification"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="languages",
            field=models.CharField(blank=True, default=" ", max_length=300),
        ),
        migrations.AddField(
            model_name="resume",
            name="location",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
