# Generated by Django 5.1.7 on 2025-04-01 04:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0003_resume_languages_resume_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="photo",
            field=models.URLField(
                blank=True, default=django.utils.timezone.now, max_length=250
            ),
            preserve_default=False,
        ),
    ]
